# SPDX-License-Identifier: GPL-2.0
# Copyright(c) 1999 - 2018 Intel Corporation.
#
# Makefile for the Intel(R) 82575 PCI-Express ethernet driver
#

obj-$(CONFIG_MXGBE) := rnp.o
rnp-objs :=   \
		rnp_main.o \
		rnp_common.o \
		rnp_debugfs.o \
		rnp_ethtool.o \
		rnp_lib.o \
		rnp_mbx.o \
		rnp_pcs.o \
		rnp_n10.o \
		rnp_n500.o \
		rnp_phy.o \
		rnp_mbx_fw.o\
		rnp_sriov.o \
		rnp_param.o \
		rnp_compat.o \
		rnp_sysfs.o \
		rnp_dcb.o \
		rnp_ptp.o \
		rnp_mpe.o